//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using Xunit;

[assembly: System.Reflection.AssemblyCompanyAttribute("SMDFe.Tests")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("SMDFe.Tests")]
[assembly: System.Reflection.AssemblyTitleAttribute("SMDFe.Tests")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: CollectionBehavior(MaxParallelThreads = 1, DisableTestParallelization = true)]

// Gerado pela classe WriteCodeFragment do MSBuild.

