//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.AppTeste.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NFe.AppTeste.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;html&gt;
        ///&lt;h1&gt;Nota Fiscal Eletrônica&lt;/h1&gt;
        ///&lt;h2&gt;Prezado Cliente,&lt;/h2&gt;
        ///&lt;p&gt;Segue anexo a Nota Fiscal eletrônica (xml e pdf), conforme pedido número 1234.&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;b&gt;Chave de acesso:&lt;/b&gt; 0123 4567 8901 2345 6789 0123 4567 8901 2345 6789 0123
        ///&lt;br&gt;&lt;b&gt;Número:&lt;/b&gt; 000123456
        ///&lt;br&gt;&lt;b&gt;Valor Total:&lt;/b&gt; 1.234,56
        ///&lt;/p&gt;
        ///&lt;p&gt;Consulte a autencidade de sua NFe acessando &lt;a href=&quot;http://www.nfe.fazenda.gov.br/portal/consulta.aspx?tipoConsulta=completa&amp;tipoConteudo=XbSeqxE8pl8=&quot;&gt;Consulta NFe Completa&lt;/a&gt; &lt;/p&gt;
        ///ZEUS Automação [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string MensagemHtml {
            get {
                return ResourceManager.GetString("MensagemHtml", resourceCulture);
            }
        }
    }
}
