//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFe.Danfe.Html {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NFe.Danfe.Html.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;page nfeArea&quot;&gt;
        ///    [marca_dagua]
        ///    &lt;div class=&quot;boxFields&quot; style=&quot;padding-top: 20px&quot;&gt;
        ///        &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///            &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td rowspan=&quot;3&quot; style=&quot;width: 30mm&quot;&gt;
        ///                        &lt;img class=&quot;client_logo&quot; src=&quot;[url_logo]&quot; alt=&quot;&quot; /&gt;
        ///                    &lt;/td&gt;
        ///                    &lt;td rowspan=&quot;3&quot;
        ///                        style=&quot;width: 46mm; font-size: 7pt&quot;
        ///                        class=&quot;txt-center&quot;&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string danfe_model_55_nfe_page_next {
            get {
                return ResourceManager.GetString("danfe_model_55_nfe_page_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Header --&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///  @media print {
        ///    @page {
        ///      margin-left: 15mm;
        ///      margin-right: 15mm;
        ///    }
        ///    footer {
        ///      page-break-after: always;
        ///    }
        ///  }
        ///
        ///  * {
        ///    margin: 0;
        ///  }
        ///
        ///  .ui-widget-content {
        ///    border: none !important;
        ///  }
        ///
        ///  .nfe-square {
        ///    margin: 0 auto 2cm;
        ///    box-sizing: border-box;
        ///    width: 2cm;
        ///    height: 1cm;
        ///    border: 1px solid #000;
        ///  }
        ///
        ///  .nfeArea.page {
        ///    width: 18cm;
        ///    position: relative;
        ///    font-family: &quot;Tim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string danfe_model_55_nfe_page_one {
            get {
                return ResourceManager.GetString("danfe_model_55_nfe_page_one", resourceCulture);
            }
        }
    }
}
